server:
    port: 8888

spring:
    application:
        name: cleanarchitecture

    datasource:
        url: jdbc:postgresql://localhost:55432/cleanarch
        driver-class-name: org.postgresql.Driver
        username: cleanarch
        password: cleanarch

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
